# Generated by Django 6.0 on 2026-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('flag_type', models.CharField(choices=[('bulk_temp_check', 'Bulk Temporary Email Checking'), ('rate_limit', 'Rate Limit Exceeded'), ('domain_abuse', 'Domain Abuse Pattern'), ('suspicious_pattern', 'Suspicious Query Pattern')], max_length=30)),
                ('severity', models.CharField(default='low', max_length=10)),
                ('details', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DomainCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('whois_country', models.CharField(blank=True, max_length=10, null=True)),
                ('spf_record', models.TextField(blank=True, null=True)),
                ('spf_found', models.BooleanField(default=False)),
                ('spf_strictness', models.CharField(blank=True, max_length=20, null=True)),
                ('dkim_found', models.BooleanField(default=False)),
                ('dkim_selector', models.CharField(blank=True, max_length=100, null=True)),
                ('dmarc_record', models.TextField(blank=True, null=True)),
                ('dmarc_found', models.BooleanField(default=False)),
                ('dmarc_policy', models.CharField(blank=True, max_length=20, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Domain caches',
            },
        ),
        migrations.CreateModel(
            name='EmailValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('is_deliverable', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='unknown', max_length=20)),
                ('threat_level', models.CharField(default='none', max_length=20)),
                ('spf_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dkim_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dmarc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['domain', 'timestamp'], name='EmailValida_domain_edf93b_idx'), models.Index(fields=['ip_address', 'timestamp'], name='EmailValida_ip_addr_07de5a_idx')],
            },
        ),
    ]
