# Generated by Django 6.0 on 2026-02-26 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('pcap_upload', 'PCAP File Upload'), ('live_capture', 'Live Packet Capture')], default='pcap_upload', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('capturing', 'Capturing Packets'), ('analyzing', 'Analyzing Flows'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('pcap_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('interface_name', models.CharField(blank=True, default='', max_length=64)),
                ('capture_duration', models.IntegerField(default=10)),
                ('total_flows', models.IntegerField(default=0)),
                ('malicious_flows', models.IntegerField(default=0)),
                ('results_json', models.TextField(default='[]')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'verbose_name_plural': 'Analysis Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
